_core:
  default_config_hash: zmkyvoZ03LGqfVeB0mtslC-pkWMOrGIU9lJl9_jqUkc
langcode: ga
dependencies:
  config:
    - filter.format.basic_html
uuid: fa95714e-d0c2-47dc-aeb3-15a3313d3191
popup_enabled: true
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
eu_countries: {  }
eu_only: false
eu_only_js: false
popup_position: false
fixed_top_position: false
popup_info:
  value: '<p>Fianáin ar shuíomh Gréasáin an Choimisinéara Teanga</p><p>Bainimid úsáid as roinnt fianán riachtanach chun an tseirbhís seo a chur ar fáil. Ba mhaith linn fianáin bhreise a shocrú ionas gur féidir linn cuimhneamh ar do chuid socruithe, tuiscint a fháil ar an dóigh a n-úsáideann daoine an tseirbhís agus feabhsuithe a dhéanamh. Ceadaíonn roinnt dár leathanaigh do thríú páirtithe roghnaithe fianáin a shocrú – mar shampla, leathanaigh ina bhfuil físeáin YouTube nó Google Maps.</p><p><a href="/node/2">Faigh tuilleadh eolais faoi mar a úsáideann muid fianáin</a></p>'
  format: basic_html
mobile_popup_info:
  value: ''
  format: basic_html
popup_info_template: new
popup_agree_button_message: 'Glac le fianáin'
popup_more_info_button_message: 'Faigh tuilleadh eolais faoi mar a úsáideann muid fianáin'
mobile_breakpoint: 768
popup_agreed_enabled: false
popup_hide_agreed: false
disagree_button_label: 'Diúltaigh d’fhianáin'
popup_agreed:
  value: '<h2>Go raibh maith agat as glacadh le fianáin</h2><p>Is féidir leat an teachtaireacht seo a chur i bhfolach anois nó tuilleadh eolais a fháil faoi fhianáin.</p>'
  format: basic_html
popup_find_more_button_message: 'More info'
popup_hide_button_message: Hide
popup_link: '<front>'
popup_link_new_window: true
popup_height: null
popup_width: ''
popup_delay: 300
show_more_info: false
popup_bg_hex: ''
popup_text_hex: ''
domain: ''
domains_option: 1
domains_list: .translate.goog
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: true
cookie_session: 0
set_cookie_session_zero_on_disagree: 0
cookie_lifetime: 365
use_mobile_message: false
use_bare_css: true
use_olivero_css: false
disagree_do_not_show_popup: false
reload_page: false
reload_options: 0
reload_routes_list: ''
cookie_name: ''
exclude_uid_1: true
better_support_for_screen_readers: true
method: opt_in
disabled_javascripts: ''
automatic_cookies_removal: true
allowed_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<p>Fianáin ar shuíomh gréasáin An Choimisinéara Gaeilge</p><p>Tá cead tugtha agat dúinn fianáin bhreise a shocrú ionas gur féidir linn cuimhneamh ar do chuid shocruithe, tuiscint a fháil ar an dóigh a n-úsáideann daoine an tseirbhís agus feabhsuithe a dhéanamh. Má tá d’intinn athraithe agat, is féidir leat do chead a tharraingt siar.</p><p><a href="/node/2">Faigh tuilleadh eolais faoin dóigh a n-úsáideann muid fianáin.</a></p>'
  format: basic_html
withdraw_tab_button_label: 'Cookie settings'
withdraw_action_button_label: 'Bain cead'
withdraw_enabled: true
withdraw_button_on_info_popup: false
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
enable_save_preferences_button: true
domain_all_sites: false
settings_tab_enabled: true
containing_element: body
cookie_policy_version: 1.0.0
cookie_value_disagreed: '0'
cookie_value_agreed_show_thank_you: '1'
cookie_value_agreed: '2'
accessibility_focus: false
close_button_action: close_banner
reject_button_label: ''
reject_button_enabled: false
close_button_enabled: false
