project_type: unity
project_name: 'Unity Svr 4'
project_id: xxxxxxxxx
project_disk_size: 8000
db_disk_size: 4000
sites:
    legalcommissionerni:
        name: 'Legal Commissioner NI'
        url: legalcommissioner-ni.org.uk
        solr: legalcommissionerni
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/legalcommissionerni ; drush core-cron'
        database: legalcommissionerni
        status: development
        default: true
    nicswell:
        name: NICSwell
        url: nicswell.co.uk
        solr: nicswell
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nicswell ; drush core-cron'
        database: nicswell
        status: development
        default: false
    autismreviewerni:
        name: 'Independent Autism Reviewer'
        url: autismreviewer-ni.org.uk
        solr: autismreviewerni
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/autismreviewerni ; drush core-cron'
        database: autismreviewerni
        status: development
        default: false
