project_type: unity
project_name: 'Unity Svr 4'
project_id: xxxxxxxxx
project_disk_size: 8000
db_disk_size: 4000
sites:
    legalcommissionerni:
        name: 'Legal Commissioner NI'
        url: legalcommissioner-ni.org.uk
        solr: legalcommissionerni
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/legalcommissionerni ; drush core-cron'
        database: legalcommissionerni
        status: production
        default: false
    nicswell:
        name: NICSwell
        url: nicswell.co.uk
        solr: nicswell
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/nicswell ; drush core-cron'
        database: nicswell
        status: development
        default: false
    autismreviewerni:
        name: 'Autism Reviewer NI'
        url: autismreviewer-ni.org.uk
        solr: autismreviewerni
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/autismreviewerni ; drush core-cron'
        database: autismreviewerni
        status: production
        default: true
    anotherway:
        name: 'Another way'
        url: another-way.org
        solr: anotherway
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/anotherway ; drush core-cron'
        database: anotherway
        status: production
        default: false
    proni:
        name: 'The Public Record Office of Northern Ireland'
        url: proni.gov.uk
        solr: proni
        www: true
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/proni ; drush core-cron'
        database: proni
        status: development
        default: false
