_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 1510ec57-1ab4-4067-86bd-a642cfd84f4f
name: 'Legal Commissioner Northern Ireland'
mail: marian@legalcommissioner-ni.org.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Legal Commissioner Northern Ireland'
frontpage_show_title: 0
