display:
  default:
    display_options:
      pager:
        options:
          tags:
            previous: '‹ foregane'
            next: 'neist ›'
            first: '« foremaist'
            last: 'hintmaist »'
