_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    sco-ulster: sco-ulster
  domains:
    en: ''
    sco-ulster: ''
selected_langcode: site_default
