_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 2a40477e-1fa4-4eb7-aabb-50ea0043de73
name: 'Office of the Commissioner of the Ulster Scots & Ulster British Tradition'
mail: noreply@email.cusubt.org.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal site'
frontpage_show_title: false
