display:
  default:
    display_options:
      empty:
        area:
          content:
            value: '<p>Níor aimsíodh torthaí.</p>'
            format: basic_html
      filters:
        search_api_fulltext:
          expose:
            label: 'Cuardaigh an suíomh seo ...'
            placeholder: 'Cuardaigh an suíomh'
