#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
'https://www.nicswell.co.uk/':
    type: upstream
    upstream: 'unity_svr_4:http'
    cache:
        enabled: 'false'
'https://nicswell.co.uk/':
    type: redirect
    to: 'https://www.nicswell.co.uk/'
'https://www.autismreviewer-ni.org.uk.{default}/':
    type: upstream
    upstream: 'unity_svr_4:http'
    cache:
        enabled: 'false'
'https://autismreviewer-ni.org.uk.{default}/':
    type: redirect
    to: 'https://www.autismreviewer-ni.org.uk.{default}/'
'https://www.proni.gov.uk/':
    type: upstream
    upstream: 'unity_svr_4:http'
    cache:
        enabled: 'false'
'https://proni.gov.uk/':
    type: redirect
    to: 'https://www.proni.gov.uk/'
'https://www.{all}/':
    type: upstream
    upstream: 'unity_svr_4:http'
    cache:
        enabled: 'false'
'https://{all}/':
    type: redirect
    to: 'https://www.{all}/'
