label: 'Featured content'
description: "<p>Defines the order of feature content to appear as part of this featured content list.</p>\r\n<p>Please note: the homepage will only show the first three items defined.</p>"
