#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
services:
    solr:
        volumes:
            - './solr-cores/legalcommissionerni:/solr-legalcommissionerni-conf'
            - './solr-cores/nicswell:/solr-nicswell-conf'
            - './solr-cores/autismreviewerni:/solr-autismreviewerni-conf'
            - './solr-cores/anotherway:/solr-anotherway-conf'
            - './solr-cores/proni:/solr-proni-conf'
        entrypoint: 'bash -c "VERBOSE=yes docker-entrypoint.sh precreate-core legalcommissionerni /solr-legalcommissionerni-conf; precreate-core nicswell /solr-nicswell-conf; precreate-core autismreviewerni /solr-autismreviewerni-conf; precreate-core anotherway /solr-anotherway-conf; precreate-core proni /solr-proni-conf; exec solr -f"'
